添加了2022暑培Java课程内容。
SAST-skill-docers/sast-skill-docs pull request #42
Opened 2023-02-10 08:51 UTC by Lethe10137

2023-02-10 10:48 UTC, abmfy commented on docs/languages/java/index.md
> +本内容根据2022年科协暑培徐晨曦同学的Java课程的讲义整理。
应有 H1 标题

2023-02-10 10:49 UTC, abmfy commented on mkdocs.yml
> +      - Tour of Java 第4章 Advanced Language Feature: languages/java/tour-of-java-chapter4-advanced-language-feature.md
标题可以省略「Tour of Java 第 x 章」

2023-02-10 10:50 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter0-introduction-and-installation.md
> ++无。
MD 语法中无序列表「+」后应有空格

2023-02-10 10:52 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter0-introduction-and-installation.md
> +**第$i$章的 CodeLab 代码位于 `codelab/chapter<i>/src`。
未封闭的「**」

2023-02-10 10:58 UTC, abmfy commented on mkdocs.yml
> +      - Tour of Java 第4章 Advanced Language Feature: languages/java/tour-of-java-chapter4-advanced-language-feature.md
文件名也是

2023-02-10 10:59 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter0-introduction-and-installation.md
> +---
代码块后应有空行，否则格式会出错

2023-02-10 11:22 UTC, abmfy requested changes
可以参考[编辑者须知](https://docs.net9.org/notes/editor/)调整排版，注意中英文之间加空格、标题的大小写格式等。
从讲义移植时可以改变部分内容的组织方式以便更适合网页阅读。

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter2-fundamental-oop.md
> +### Using interface
统一标题大小写规则，最好每个单词首字母大写

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter2-fundamental-oop.md
> +- Enum 类 ：[java.lang.Enum<E>](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Enum.html)
统一使用某一种冒号，冒号前不加空格，半角冒号后加空格

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +???+ 关于JEP
```
???+ note "关于 JEP"
```

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +- *record*类的成员变量隐式为`final`。
中英文之间加空格

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +-
多了一行

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +你可以使用Java标准库中提供的异常类，请参见[API Ref](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Exception.html)中的`Direct Known Subclasses`小节寻找是否有自己需要的异常类。
中英文之间加空格

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +为了解决这种情况，Java引入了通配符类型`?`，用于表示类型参数的派生：
中英文之间加空格

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter4-advanced-language-feature.md
> +Switch Expressions [JEP361]https://openjdk.org/jeps/361
可以加下超链接

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter0-introduction-and-installation.md
> +- **太长不看版**
这里「太长不看版」应是解释上面的「TLDR」？从讲义搬过来时可以对格式作调整以更适合网页阅读

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter1-basic-language-structure.md
> +- JEP https://openjdk.org/jeps
可以整理成超链接，其他文档的资源链接同

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/tour-of-java-chapter2-fundamental-oop.md
> +- （非必须）C++、python等语言的 OOP 语法。
- Python 首字母大写
- Python 后加空格

2023-02-10 11:22 UTC, abmfy commented on docs/languages/java/index.md
> +相关链接：2022年科协暑培的Android项目示例（Java 语言）。 https://github.com/xsun2001/simple-tree-hole-android
中英文之间加空格，参考[编辑者须知](https://docs.net9.org/notes/editor/#_9)

2023-02-10 15:24 UTC, Lethe10137 commented
> 可以参考[编辑者须知](https://docs.net9.org/notes/editor/)调整排版，注意中英文之间加空格、标题的大小写格式等。 从讲义移植时可以改变部分内容的组织方式以便更适合网页阅读。

我没有找到关于标题中大小写的规定。

2023-02-11 14:36 UTC, abmfy approved these changes

2023-02-11 14:36 UTC, merged